name: Build and deploy iOS app

on:
  pull_request:
    branches:
      - dev
      - staging
      - production
    paths:
      - "**/*"

jobs:
  ios-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Remove existing lock file
        run: rm -f package-lock.json

      - name: Install dependencies
        run: |
          npm install
          npm install expo@latest react-native@latest

      - name: Generate iOS Project
        run: npx expo prebuild --platform ios --clean

      - name: Install CocoaPods
        run: |
          brew install cocoapods
          pod --version

      - name: Install Pod Dependencies
        working-directory: ios
        run: |
          pod install
          ls -la

      - name: Build iOS
        working-directory: ios
        run: |
          xcodebuild -workspace MyApp.xcworkspace \
          -scheme MyApp \
          -configuration Release \
          -archivePath $PWD/build/MyApp.xcarchive \
          archive
